# -*- coding: utf-8 -*-
"""Practica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ko353rA9BuhghoO8rYqAoO3M68ecNRuC
"""

import pandas as pd
def combine_two_tables(person: pd.DataFrame, address: pd.DataFrame) -> pd.DataFrame:
 return( pd.merge(person,address,on='personId',how='left')[['firstName', 'lastName', 'city', 'state']]) #Como hacer merge en 2 tablas

import kagglehub
from kagglehub import KaggleDatasetAdapter
# Download latest version
path = kagglehub.dataset_download("saidaminsaidaxmadov/chocolate-sales")

print("Path to dataset files:", path)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
data = pd.read_csv("/kaggle/input/chocolate-sales/Chocolate Sales (2).csv")
data.head(20)

data.isnull().sum()

#df["XX"] = ["XX"].str.strip(.-_123) para limpiar columnas
#df["XX"] = ["XX"].str.replace("^XX-XX", "")
#df.describe() te da media,mediana, desv estandar
#df.info() te da la informacion de tu csv

data.sort_values(by= "Country", ascending=True).head()

data.groupby("Country").count()

# Variables in Python

first_name = 'Asabeneh'
last_name = 'Yetayeh'
country = 'Finland'
city = 'Helsinki'
age = 250
is_married = True
skills = ['HTML', 'CSS', 'JS', 'React', 'Python']
person_info = {
    'firstname': 'Asabeneh',
    'lastname': 'Yetayeh',
    'country': 'Finland',
    'city': 'Helsinki'
}

# Printing the values stored in the variables

print('First name:', first_name)
print('First name length:', len(first_name))
print('Last name: ', last_name)
print('Last name length: ', len(last_name))
print('Country: ', country)
print('City: ', city)
print('Age: ', age)
print('Married: ', is_married)
print('Skills: ', skills)
print('Person information: ', person_info)

# Declaring multiple variables in one line

first_name, last_name, country, age, is_married = 'Asabeneh', 'Yetayeh', 'Helsink', 250, True

print(first_name, last_name, country, age, is_married)
print('First name:', first_name)
print('Last name: ', last_name)
print('Country: ', country)
print('Age: ', age)
print('Married: ', is_married)

